name: CI - Cesta Básica App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    name: Setup do Ambiente
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validar importações
        run: |
          python - << 'EOF'
          import pandas, numpy, dash, plotly, xgboost
          print("Imports OK")
          EOF

  train:
    name: Executar Pipeline de Treino
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar train_model.py
        run: |
          echo "Executando pipeline de treino..."
          python train_model.py

      - name: Publicar artefatos do treino
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-treino
          path: artifacts/

  docker-build:
    name: Build da Imagem Docker
    runs-on: ubuntu-latest
    needs: train
  
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
  
      - name: Build da imagem Docker
        run: |
          docker build -t cestabasica:ci .
  
      - name: Teste rápido (smoke test)
        run: |
          docker run --rm cestabasica:ci python -c "print('Container OK')"
  
      - name: Publicar logs do Docker
        run: |
          docker history cestabasica:ci > docker_history.txt
          cat docker_history.txt
  
      - name: Upload dos logs
        uses: actions/upload-artifact@v4
        with:
          name: docker-logs
          path: docker_history.txt


  finalize:
    name: Finalização
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - name: Mensagem final
        run: echo "✅ Pipeline CI concluído com sucesso!"
